# Generated by Django 5.0.6 on 2024-05-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_categoria_options_alter_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='Categorias',
        ),
    ]
