# Generated by Django 5.0.6 on 2024-06-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_productostiendas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productostiendas',
            table='ProductosTiendas',
        ),
    ]
