# Generated by Django 5.0.6 on 2024-06-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productostiendas',
            options={'verbose_name': 'Producto en Tienda', 'verbose_name_plural': 'Productos en Tiendas'},
        ),
        migrations.AlterField(
            model_name='productostiendas',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=50, verbose_name='Estado'),
        ),
    ]
