# Generated by Django 5.0.6 on 2024-06-29 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_proveedor_alter_categoria_table_producto_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='productostiendas',
            name='proveedor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapp.proveedor', verbose_name='Proveedor'),
            preserve_default=False,
        ),
    ]
