# Generated by Django 5.0.6 on 2024-06-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_producto_proveedor_productostiendas_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(default=2, max_length=100, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
