# Generated by Django 5.0.6 on 2024-06-29 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_proveedor_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre',
        ),
    ]
