# Generated by Django 5.0.6 on 2024-07-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_proveedor_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default=2, max_length=50, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
