# Generated by Django 5.0.6 on 2024-07-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_cliente_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='tienda_logos/'),
        ),
    ]
