# Generated by Django 5.0.6 on 2024-08-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_cliente_user_alter_productostiendas_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productostiendas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos_tiendas/', verbose_name='Imagen del Producto'),
        ),
    ]
