# Generated by Django 5.0.6 on 2024-09-07 14:36

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_productostiendas_imagen'),
    ]

    operations = [
        # Comentado o eliminado si el campo 'direccion' no existe en 'Cliente'
        # migrations.RemoveField(
        #     model_name='cliente',
        #     name='direccion',
        # ),
        migrations.AddField(
            model_name='cliente',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_clientes/'),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('pais', models.CharField(default='Colombia', max_length=100)),
                ('principal', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='myapp.cliente')),
            ],
            options={
                'db_table': 'Direccion',
            },
        ),
    ]
