# Generated by Django 5.0.6 on 2024-09-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_cliente_direccion_cliente_imagen_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='pais',
        ),
    ]
