# Generated by Django 5.0.6 on 2024-09-07 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tienda',
            options={'verbose_name': 'Tienda', 'verbose_name_plural': 'Tiendas'},
        ),
        migrations.AddField(
            model_name='direccion',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='myapp.tienda'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='myapp.cliente'),
        ),
    ]
