# Generated by Django 5.0.6 on 2024-09-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_tienda_options_direccion_tienda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagen_perfil',
            field=models.ImageField(default='default/Defaul.jpg', upload_to='imagenes_clientes/'),
        ),
    ]
