# Generated by Django 5.0.6 on 2024-09-08 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_cliente_imagen_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productostiendas',
            name='usuario',
        ),
        migrations.AddField(
            model_name='productostiendas',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos_tiendas', to='myapp.tienda'),
            preserve_default=False,
        ),
    ]
