# Generated by Django 5.0.6 on 2024-09-11 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_productostiendas_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='direccion',
        ),
    ]
