# Generated by Django 5.0.6 on 2024-09-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_tienda_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='tipo_descuento',
            field=models.CharField(blank=True, choices=[('porcentaje', 'Porcentaje'), ('valor_fijo', 'Valor Fijo')], max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='promocion',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('tienda',), name='unique_active_promotion_per_store'),
        ),
    ]
