# Generated by Django 5.0.6 on 2024-09-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_promocion_tipo_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
