# Generated by Django 5.0.6 on 2024-09-12 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_promocion_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='tipo_descuento',
        ),
    ]
