# Generated by Django 5.0.6 on 2024-09-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_orden_productoorden'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orden',
            table='ordenes',
        ),
    ]
