# Generated by Django 5.0.6 on 2024-09-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_orden_iva_orden_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='producto_tienda',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='tienda',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.AlterModelOptions(
            name='atencioncliente',
            options={'verbose_name': 'Atención al Cliente', 'verbose_name_plural': 'Atención al Cliente'},
        ),
        migrations.RenameField(
            model_name='atencioncliente',
            old_name='descripcion',
            new_name='mensaje',
        ),
        migrations.RemoveField(
            model_name='atencioncliente',
            name='asunto',
        ),
        migrations.RemoveField(
            model_name='metodopago',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='productoorden',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='atencioncliente',
            name='estado_atencion',
            field=models.CharField(choices=[('no_leido', 'No Leído'), ('leido', 'Leído'), ('respondido', 'Respondido')], default='no_leido', max_length=50),
        ),
        migrations.AddField(
            model_name='atencioncliente',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atencioncliente',
            name='tienda',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='atencion_cliente', to='myapp.tienda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metodopago',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='myapp.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metodopago',
            name='detalles',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metodopago',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('transferencia_bancaria', 'Transferencia Bancaria'), ('paypal', 'PayPal')], default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atencioncliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atencion_cliente', to='myapp.cliente'),
        ),
        migrations.AlterField(
            model_name='atencioncliente',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='imagen_perfil',
            field=models.ImageField(default='default/Defaut.jpg', upload_to='imagenes_clientes/'),
        ),
        migrations.AlterField(
            model_name='productoorden',
            name='producto_tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_orden', to='myapp.productostiendas'),
        ),
        migrations.AlterModelTable(
            name='atencioncliente',
            table='atencion_cliente',
        ),
        migrations.AlterModelTable(
            name='metodopago',
            table='metodo_pago',
        ),
        migrations.AlterModelTable(
            name='productoorden',
            table='productos_orden',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
