# Generated by Django 5.0.6 on 2024-09-16 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_alter_direccion_ciudad_alter_direccion_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='nueva_ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.ciudad'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='nueva_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.departamento'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='departamento',
            field=models.CharField(max_length=100),
        ),
    ]
