# Generated by Django 5.0.6 on 2024-09-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_direccion_nueva_ciudad_direccion_nueva_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='nueva_ciudad',
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='nueva_departamento',
        ),
    ]
