# Generated by Django 5.0.6 on 2024-09-16 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_remove_direccion_nueva_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.ciudad'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.departamento'),
        ),
    ]
