# Generated by Django 5.0.6 on 2024-09-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_direccion_ciudad_alter_direccion_departamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelTable(
            name='ciudad',
            table='Ciudad',
        ),
        migrations.AlterModelTable(
            name='departamento',
            table='Departamento',
        ),
    ]
