# Generated by Django 5.0.6 on 2024-09-16 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_alter_ciudad_options_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='usuario',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tienda',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='myapp.tienda'),
            preserve_default=False,
        ),
    ]
