# Generated by Django 5.0.6 on 2024-09-20 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_remove_proveedor_usuario_proveedor_tienda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('administrador', 'Administrador'), ('cliente', 'Cliente'), ('tienda', 'Tienda')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Rol',
            },
        ),
        migrations.AlterModelOptions(
            name='tienda',
            options={},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='user',
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='myapp.rol')),
            ],
            options={
                'db_table': 'Perfil',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='perfil',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='myapp.perfil'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tienda',
            name='perfil',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='tienda', to='myapp.perfil'),
            preserve_default=False,
        ),
    ]
