# Generated by Django 5.0.6 on 2024-09-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_rol_alter_tienda_options_remove_cliente_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='cantidad_maxima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='cantidad_minima',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='codigo_promocional',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='condiciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promocion',
            name='productos_aplicables',
            field=models.ManyToManyField(related_name='promociones', to='myapp.productostiendas'),
        ),
    ]
