# Generated by Django 5.0.6 on 2024-09-29 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_promocion_cantidad_maxima_promocion_cantidad_minima_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
