# Generated by Django 5.0.6 on 2024-09-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_alter_promocion_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promocion',
            name='unique_active_promotion_per_store',
        ),
    ]
