# Generated by Django 5.0.6 on 2024-09-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_remove_promocion_unique_active_promotion_per_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocion',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Promoción', 'verbose_name_plural': 'Promociones'},
        ),
    ]
