# Generated by Django 5.0.6 on 2024-10-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_alter_promocion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostiendas',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='productostiendas',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10, verbose_name='Estado'),
        ),
        migrations.AddIndex(
            model_name='productostiendas',
            index=models.Index(fields=['estado'], name='ProductosTi_estado_32d5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='productostiendas',
            index=models.Index(fields=['precio_unitario'], name='ProductosTi_precio__24593c_idx'),
        ),
        migrations.AddConstraint(
            model_name='productostiendas',
            constraint=models.UniqueConstraint(fields=('producto', 'proveedor', 'tienda'), name='unique_prod_prov_tienda'),
        ),
    ]
