# Generated by Django 5.0.6 on 2024-10-11 06:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_alter_productostiendas_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.perfil'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.CharField(default=3, max_length=10, validators=[django.core.validators.RegexValidator(message='Formato de código postal no válido', regex='^[0-9]{5}(?:-[0-9]{4})?$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cliente'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='direccion_envio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.direccion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tienda',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.perfil'),
        ),
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together={('tienda', 'razon_social')},
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cliente')),
                ('direccion_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.direccion')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tienda')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo')], max_length=50)),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.cliente')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.pedido')),
                ('productos_tiendas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productostiendas')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tienda')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productos_tiendas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.productostiendas')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.venta')),
            ],
        ),
    ]
