# Generated by Django 5.0.6 on 2024-10-11 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_alter_cliente_perfil_alter_direccion_codigo_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='direccion_envio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tienda',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='productos_tiendas',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='tienda',
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_venta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.promocion'),
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
