# Generated by Django 5.0.6 on 2024-10-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_remove_pedido_cliente_remove_pedido_direccion_envio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='descuento',
        ),
        migrations.AddField(
            model_name='promocion',
            name='descuento_porcentaje',
            field=models.IntegerField(default=2, help_text='Porcentaje de descuento (ej: 20 para 20%)'),
            preserve_default=False,
        ),
    ]
