# Generated by Django 5.0.6 on 2024-10-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_remove_promocion_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='descuento_porcentaje',
            field=models.IntegerField(help_text='Porcentaje de descuento (ej: 20%)'),
        ),
    ]
