# Generated by Django 5.0.6 on 2024-10-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_alter_promocion_descuento_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
    ]
