# Generated by Django 5.0.6 on 2024-11-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_alter_promocion_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='promociones/'),
        ),
    ]
