# Generated by Django 5.0.6 on 2024-11-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_promocion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
