# Generated by Django 5.1.4 on 2025-01-28 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_categoria_icono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodopago',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta_crédito/débito', 'Tarjeta de crédito/débito'), ('transferencia_bancaria', 'Transferencia Bancaria'), ('paypal', 'PayPal'), ('pago_contra_entrega', 'Pago contra entrega (COD)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orden',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='myapp.metodopago'),
        ),
    ]
