# Generated by Django 5.1.4 on 2025-01-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_remove_metodopago_tipo_alter_metodopago_metodo_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metodopago',
            name='cliente',
        ),
    ]
