# Generated by Django 5.1.4 on 2025-01-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_remove_metodopago_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metodopago',
            options={'verbose_name': 'Método de Pago', 'verbose_name_plural': 'Métodos de Pago'},
        ),
        migrations.RemoveField(
            model_name='metodopago',
            name='detalles',
        ),
        migrations.RemoveField(
            model_name='metodopago',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='metodopago',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
