# Generated by Django 5.1.4 on 2025-01-28 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_alter_metodopago_options_remove_metodopago_detalles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='metodo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.metodopago'),
        ),
    ]
