# Generated by Django 5.1.4 on 2025-01-29 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_alter_orden_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Formato de código postal no válido', regex='^[0-9]{5}(?:-[0-9]{4})?$')]),
        ),
    ]
