# Generated by Django 5.1.4 on 2025-04-26 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_alter_perfil_rol_alter_perfil_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='perfil',
            table=None,
        ),
    ]
