from django.urls import path, include
from .views import hello, eliminar_proveedor, index_administrador, index_tienda, logout_view, register, home, perfil_cliente, categoria, index_producto, index_proveedor, asignar_proveedor, perfil_tienda, index_cliente, login_view, busqueda_tiendas, busqueda_productos, get_datos, unauthorized
from . import views
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', home, name='home'),
    path('accounts/login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('index_tienda/', index_tienda, name='index_tienda'),
    path('register/', views.register, name='register'),
    path('perfil_cliente/', views.perfil_cliente, name='perfil_cliente'),
    path('perfil_tienda/', perfil_tienda, name='perfil_tienda'),
    path('index_cliente/', index_cliente, name='index_cliente'),
    path('index_administrador/', index_administrador, name='index_administrador'),
    path('categorias/', categoria, name='categorias'),
    path('asignar_producto/', views.asignarProducto, name='asignar_producto'),
    path('index_producto/', index_producto, name='index_producto'),
    path('buscar_producto/', views.buscar_producto, name='buscar_producto'),
    path('index_producto/actualizar_producto/<int:id>/', views.actualizar_producto, name='actualizar_producto'),
    path('index_producto/actualizar_producto/', views.actualizar_producto, name='actualizar_producto_list'),
    path('index_producto/eliminar_producto/<int:id>/', views.eliminar_producto, name='eliminar_producto'),
    path('index_proveedor/', index_proveedor, name='index_proveedor'),
    path('asignar_proveedor/', views.asignar_proveedor),
    path('index_proveedor/eliminar_proveedor/<int:id>/', views.eliminar_proveedor, name='eliminar_proveedor'),
    path('index_proveedor/actualizar_proveedor/<int:id>/', views.actualizar_proveedor, name='actualizar_proveedor'),
    path('busqueda_tiendas/', busqueda_tiendas, name='busqueda_tiendas'),
    path('productos/busqueda_productos/<int:tienda_id>/', busqueda_productos, name='busqueda_productos'),
    path('confirmar_pago/', views.confirmar_pago, name='confirmar_pago'),
    path('api/crear_direccion/', views.crear_direccion, name='crear_direccion'),
    path('api/crear_orden/', views.crear_orden, name='crear_orden'),
    path('direccion/', views.direccion, name='direccion'),
    path('registrar-direccion/', views.registrar_direccion, name='registrar_direccion'),
    path('eliminar_direccion/<int:direccion_id>/', views.eliminar_direccion, name='eliminar_direccion'),
    path('actualizar_direccion/<int:direccion_id>/', views.actualizar_direccion, name='actualizar_direccion'),
    path('get-datos/', get_datos, name='get_datos'),
    path('promocion/', views.promocion, name='promocion'),
    path('promocion/editar/<int:id>/', views.editar_promocion, name='editar_promocion'),
    path('promocion/eliminar/<int:id>/', views.eliminar_promocion, name='eliminar_promocion'),
    path('historial_compra/', views.historial_compra, name='historial_compra'),
    path('inventario/', views.inventario, name='inventario'),
    path('ordenes/', views.ordenes, name='ordenes'),
    path('unauthorized/', unauthorized, name='unauthorized'),
    path('agregar_al_carrito/<int:producto_tienda_id>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('factura/<int:orden_id>/', views.descargar_factura, name='descargar_factura'),
    path('reporte_tienda/', views.reporte_tienda, name='reporte_tienda'),
    path('cambiar_estado_orden/<int:id>/', views.cambiar_estado_orden, name='cambiar_estado_orden'),
    path('configuracion_tienda/', views.configuracion_tienda, name='configuracion_tienda'),
    path('ver_promociones_activas/', views.ver_promociones_activas, name='ver_promociones_activas'),
    path('atencion_cliente/', views.atencion_cliente, name='atencion_cliente'),
    path('seguimiento_pedido/<int:orden_id>/', views.seguimiento_pedido, name='seguimiento_pedido'),
    path('guardar_mensaje/', views.guardar_mensaje, name='guardar_mensaje'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
